"""Stage 4 — SAR (Suspicious Activity Report) draft generation.

Pipeline position:
    DebateVerdict (ESCALATE) → **SARDraft** → human review
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from app.schemas.common import EvidenceItem


class SARDraft(BaseModel):
    """Auto-generated SAR narrative ready for compliance officer review."""

    client_id: int
    subject_information: str = Field(
        ...,
        description="Structured summary of the subject: name, type, jurisdiction, account(s)",
    )
    narrative: str = Field(
        ...,
        description="Free-text SAR narrative describing the suspicious activity",
    )
    red_flags: list[str] = Field(
        default_factory=list,
        description="Concise bullet-point red flags, e.g. 'Structuring below reporting threshold'",
    )
    regulatory_basis: list[str] = Field(
        default_factory=list,
        description="GDPR articles or regulations that apply, e.g. 'GDPR Article 6'",
    )
    recommended_action: str = Field(
        ..., description="Proposed next step: file SAR, enhanced monitoring, account freeze, etc."
    )
    evidence_appendix: list[EvidenceItem] = Field(
        default_factory=list,
        description="Full evidence chain backing the narrative",
    )
    disclaimer: str = Field(
        default="This report was generated by an AI system and must be reviewed by a qualified compliance officer before submission.",
        description="Legal / compliance disclaimer",
    )
